zuul:
  prefix: /api
  routes:
    FarmerService:
      path: /farmer/**
      serviceId: FarmerService
      url : http://localhost:8082/


server:
  port: 9000

spring:
  application:
    name: Api-Service
  data:
    mongodb:
      uri: mongodb+srv://raghavendra:power5678@cropsdeal.3pb5k.mongodb.net/security


eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true
    register-with-eureka: true
