server:
    port: 8085
spring:
    data:
        mongodb:
            uri: mongodb+srv://raghavendra:power5678@cropsdeal.3pb5k.mongodb.net/mainservice
    application:
        name: AdminService
    mvc:
        pathmatch:
            matching-strategy:
                ant-path-matcher