server:
  port: 8083
spring:
  data:
    mongodb:
      uri: mongodb+srv://raghavendra:power5678@cropsdeal.3pb5k.mongodb.net/dealers
  application:
    name: DealerService
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher